<?php
/**
 * Created by PhpStorm.
 * User: Trent
 * Date: 11/11/2017
 * Time: 2:20 PM
 */

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity
 * @ORM\Table(name="`user`")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string",nullable =true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string",nullable =true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string",nullable =true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="Message",mappedBy="user")
     */
    private $messages;


    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }


    /**
     * @return ArrayCollection|Message[]
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    /**
     * @return mixed
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @param mixed $firstname
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    public function getUsername()
    {
        return parent::getUsername(); // TODO: Change the autogenerated stub
    }

    public function getRoles()
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }

    public function getPassword()
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }

    public function getSalt()
    {
        return parent::getSalt(); // TODO: Change the autogenerated stub
    }

    public function eraseCredentials()
    {
        parent::eraseCredentials(); // TODO: Change the autogenerated stub
    }

    public function getEmail()
    {
        return parent::getEmail(); // TODO: Change the autogenerated stub
    }

    public function setEmail($email)
    {
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }
}